---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.remediation.security.role }}
  namespace: {{ .Values.remediation.security.namespace_ic }}
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - list
      - delete
      - watch
