---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.remediation.security.rolebinding }}
  namespace: {{ .Values.remediation.security.namespace_ic }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.remediation.security.role }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.remediation.security.serviceaccount }}
    namespace: {{ .Values.remediation.security.namespace_remediate }}
